apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-shell
data:
  provision.sh: |- {{  .Files.Get "scripts/shell/provision.sh" | nindent 4 }}
  healthcheck.sh: |- {{  .Files.Get "scripts/shell/healthcheck.sh" | nindent 4 }}
  install-groovy.sh: |- {{  .Files.Get "scripts/shell/install-groovy.sh" | nindent 4 }}