apiVersion: v1
kind: ConfigMap
metadata:
  name: groovy-configmap
data:
  docker.groovy: {{ .Files.Get "docker.groovy"}} 
  golang.groovy: {{ .Files.Get "golang.groovy"}} 
  ldap.groovy: {{ .Files.Get "ldap.groovy"}} 
  npm.groovy: {{ .Files.Get "npm.groovy"}} 
  
