apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-groovy
data:
  docker.groovy: |- {{  .Files.Get "scripts/groovy/docker.groovy" | nindent 4 }}
  npm.groovy: |- {{  .Files.Get "scripts/groovy/npm.groovy" | nindent 4 }}
  nuget.groovy: |- {{  .Files.Get "scripts/groovy/nuget.groovy" | nindent 4 }}
  security.groovy: |- {{  .Files.Get "scripts/groovy/security.groovy" | nindent 4 }}
  ldap.groovy: |- {{  .Files.Get "scripts/groovy/ldap.groovy" | nindent 4 }}
  cleanup.groovy: |- {{  .Files.Get "scripts/groovy/cleanup.groovy" | nindent 4 }}
  realms.groovy: |- {{  .Files.Get "scripts/groovy/realms.groovy" | nindent 4 }}