apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus
data:
  docker.groovy: |
    {{ .Files.Get "scripts/groovy/docker.groovy" }}
  golang.groovy: |
    {{ .Files.Get "scripts/groovy/golang.groovy" }}
  ldap.groovy: |
    {{ .Files.Get "scripts/groovy/ldap.groovy" }}
  npm.groovy: |
    {{ .Files.Get "scripts/groovy/npm.groovy" }}
  

