apiVersion: v1
kind: ConfigMap
metadata:
  name: groovy-configmap
data:
  docker.groovy: {{ .Files.Get "/scripts/docker.groovy"}} 
  golang.groovy: {{ .Files.Get "/scripts/golang.groovy"}} 
  ldap.groovy: {{ .Files.Get "/scripts/ldap.groovy"}} 
  npm.groovy: {{ .Files.Get "/scripts/npm.groovy"}} 
  
