apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nexus
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - image: sonatype/nexus3
        imagePullPolicy: Never
        name: nexus
        volumeMounts:
        - mountPath: /opt/sonatype/nexus
          name: nexus-data
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
      - args:
        - sh
        - /scripts/script.sh
        image: busybox
        imagePullPolicy: Never
        command: []
        name: sidecar1
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /scripts
          name: scripts
        - mountPath: /opt/sonatype/nexus
          name: nexus-data
      volumes:
      - name: scripts
        configMap:
          name: nexus
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus
      restartPolicy: Always