apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nexus
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - image: sonatype/nexus3
        imagePullPolicy: Always
        name: nexus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
      - args:
        - sh
        - /script.sh
        image: busybox
        imagePullPolicy: Always
        command: []
        name: sidecar1
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /
          name: nexus-configmap
      restartPolicy: Always