apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nexus
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - image: sonatype/nexus3
        imagePullPolicy: Never
        name: nexus
        volumeMounts:
        - mountPath: /opt/sonatype
          name: start-script
        - mountPath: /config
          name: config
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
      volumes:
      - name: config
        configMap:
          name: nexus
      - name: start-script
        configMap:
          name: nexus-start-script
          defaultMode: 0777
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus
      restartPolicy: Always