apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  storageClassName: vsphere-thin
  volumeMode: Filesystem
